### PR TITLE
Add example notebook to read multiple `.nc` files and plot an echogram

### PR DESCRIPTION
**Pull request by valentina-s**
This notebook contains an example how to read a few `.nc` files and plot an echogram. The format does not have calibration variables, so feel free to change to newer files.

### CODE REVIEW

**Comment by leewujung** [comment]
@valentina-s : Thanks for the PR! 
I have a few suggestions:
- could you change the output color limits to -80 to -40 dB, to make things show up more?
- change colormap to use a monotonic linear one instead of diverging one
- add a cell explaining that the selected/plotted echogram is at 18 kHz
- change `.isel(frequency=0)` to `.sel(frequency=180e3)` so that it is explicit what the selection is based on

**Comment by valentina-s** [comment]
Added those details.

**Comment by leewujung** [comment]
I tweaked and expanded the cell explaining the dimensions/data variables in the plot a bit. 

Will merge this now so `main` is updated.

**Comment by valentina-s** [comment]
That made the Colab notebook out of date. It is not that important to maintain both, but I thought it would be good to have it if some contributors are having trouble plotting the files on their laptop.

**Comment by leewujung** [comment]
Oh I was just editing locally. Could you copy paste that cell? I only changed the text and nothing else.

**Pull request merged**
