### PR TITLE
Merge dev(version 0.1.0) into main

### PR DESCRIPTION
**Pull request by ldr426**

### CODE REVIEW

**Comment by valentina-s** [comment]
Thanks @ldr426 I made a small PR with a few changes.

I also noticed that the pictures in the echogram notebook of the box selection do not render in the read the docs version.  Could you see if they will be ok?

The curtain plot does not show in the static notebook. Is there a way to make it display so people get an idea of how the plot looks like if they have not heard of "curtain".

**Review by valentina-s — COMMENTED** [review]
* Thanks @ldr426 I made a small PR with a few changes. Please check them and merge to dev, before merging to main.

* I also noticed that the pictures in the echogram notebook of the box selection do not render in the read the docs version.  Could you see if they will be ok?
Screenshot 2023-09-22 at 4 48 51 PM


* The curtain plot does not show in the static notebook. Is there a way to make it display so people get an idea of how the plot looks like if they have not heard of "curtain".

**Comment by ldr426** [comment]
> * Thanks @ldr426 I made a small PR [Dev patch #147](https://github.com/OSOceanAcoustics/echoshader/pull/147) with a few changes. Please check them and merge to dev, before merging to main.
> * I also noticed that the pictures in the echogram notebook of the box selection do not render in the read the docs version.  Could you see if they will be ok?
> 
> Screenshot 2023-09-22 at 4 48 51 PM
> * The curtain plot does not show in the static notebook. Is there a way to make it display so people get an idea of how the plot looks like if they have not heard of "curtain".

@valentina-s  Thanks for PR with the changes! 
- For the second point, I can view it rendered on my device. Let's consider saving pictures in a dedicated folder instead of solely within the IPython Notebook file.
- For the third point, I've made a few attempts to save the rendered curtain in the static file, but unfortunately, I've encountered some failures. As a workaround, I suggest showing users an example picture for now.

**Comment by valentina-s** [comment]
@ldr426 could you resolve the conflicts and we can merge into main. Then I will add a patch to reverse the axes so the echograms are plotted in the right orientation #108 .

**Review by valentina-s — APPROVED** [review]

**Comment by valentina-s** [comment]
This PR closes #144.

**Pull request merged**
